#debug: true
logging:
  path: V1.0.0/logs
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    name: druid
    password: RooT@Hj01
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/gndc?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
