package com.gndc.core.model;

import com.gndc.common.model.BaseEntity;
import lombok.Getter;
import lombok.Setter;
import tk.mybatis.mapper.annotation.LogicDelete;

import javax.persistence.*;
import java.util.Date;
import java.util.List;
@Getter
@Setter
@Table(name = "dc_admin")
public class Admin extends BaseEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin.oper_id
     *
     * @mbggenerated Sat Feb 23 14:14:44 CST 2019
     */
    private Integer operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin.name
     *
     * @mbggenerated Sat Feb 23 14:14:44 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin.login_name
     *
     * @mbggenerated Sat Feb 23 14:14:44 CST 2019
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin.email
     *
     * @mbggenerated Sat Feb 23 14:14:44 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin.password
     *
     * @mbggenerated Sat Feb 23 14:14:44 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin.password_sign
     *
     * @mbggenerated Sat Feb 23 14:14:44 CST 2019
     */
    private String passwordSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin.operate_sign
     *
     * @mbggenerated Sat Feb 23 14:14:44 CST 2019
     */
    private String operateSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin.is_lock
     *
     * @mbggenerated Sat Feb 23 14:14:44 CST 2019
     */
    private Byte isLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin.lock_time
     *
     * @mbggenerated Sat Feb 23 14:14:44 CST 2019
     */
    private Date lockTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin.login_count
     *
     * @mbggenerated Sat Feb 23 14:14:44 CST 2019
     */
    private Integer loginCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin.last_login_time
     *
     * @mbggenerated Sat Feb 23 14:14:44 CST 2019
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin.last_login_ip
     *
     * @mbggenerated Sat Feb 23 14:14:44 CST 2019
     */
    private String lastLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin.last_logout_time
     *
     * @mbggenerated Sat Feb 23 14:14:44 CST 2019
     */
    private Date lastLogoutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin.telephone
     *
     * @mbggenerated Sat Feb 23 14:14:44 CST 2019
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin.phone
     *
     * @mbggenerated Sat Feb 23 14:14:44 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin.level
     *
     * @mbggenerated Sat Feb 23 14:14:44 CST 2019
     */
    private Byte level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin.partner_id
     *
     * @mbggenerated Sat Feb 23 14:14:44 CST 2019
     */
    private Integer partnerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin.role_id
     *
     * @mbggenerated Sat Feb 23 14:14:44 CST 2019
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin.status
     *
     * @mbggenerated Sat Feb 23 14:14:44 CST 2019
     */
    @LogicDelete(notDeletedValue = 1, isDeletedValue = -1)
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin.create_admin_id
     *
     * @mbggenerated Sat Feb 23 14:14:44 CST 2019
     */
    private Integer createAdminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin.update_admin_id
     *
     * @mbggenerated Sat Feb 23 14:14:44 CST 2019
     */
    private Integer updateAdminId;

    @Transient
    private List<Right> rights;

}