package com.gndc.core.model;

import com.gndc.common.model.BaseEntity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;
@Table(name = "dc_admin_events")
public class AdminEvents extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin_events.id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin_events.admin_id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin_events.role_id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin_events.event_type
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer eventType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin_events.event_time
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Date eventTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin_events.ip_address
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String ipAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_admin_events.remark
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_admin_events.id
     *
     * @return the value of dc_admin_events.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_admin_events.id
     *
     * @param id the value for dc_admin_events.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_admin_events.admin_id
     *
     * @return the value of dc_admin_events.admin_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_admin_events.admin_id
     *
     * @param adminId the value for dc_admin_events.admin_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_admin_events.role_id
     *
     * @return the value of dc_admin_events.role_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_admin_events.role_id
     *
     * @param roleId the value for dc_admin_events.role_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_admin_events.event_type
     *
     * @return the value of dc_admin_events.event_type
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_admin_events.event_type
     *
     * @param eventType the value for dc_admin_events.event_type
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setEventType(Integer eventType) {
        this.eventType = eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_admin_events.event_time
     *
     * @return the value of dc_admin_events.event_time
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Date getEventTime() {
        return eventTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_admin_events.event_time
     *
     * @param eventTime the value for dc_admin_events.event_time
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setEventTime(Date eventTime) {
        this.eventTime = eventTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_admin_events.ip_address
     *
     * @return the value of dc_admin_events.ip_address
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_admin_events.ip_address
     *
     * @param ipAddress the value for dc_admin_events.ip_address
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_admin_events.remark
     *
     * @return the value of dc_admin_events.remark
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_admin_events.remark
     *
     * @param remark the value for dc_admin_events.remark
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_admin_events
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AdminEvents other = (AdminEvents) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getAdminId() == null ? other.getAdminId() == null : this.getAdminId().equals(other.getAdminId()))
                && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
                && (this.getEventType() == null ? other.getEventType() == null : this.getEventType().equals(other.getEventType()))
                && (this.getEventTime() == null ? other.getEventTime() == null : this.getEventTime().equals(other.getEventTime()))
                && (this.getIpAddress() == null ? other.getIpAddress() == null : this.getIpAddress().equals(other.getIpAddress()))
                && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_admin_events
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAdminId() == null) ? 0 : getAdminId().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getEventType() == null) ? 0 : getEventType().hashCode());
        result = prime * result + ((getEventTime() == null) ? 0 : getEventTime().hashCode());
        result = prime * result + ((getIpAddress() == null) ? 0 : getIpAddress().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_admin_events
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", adminId=").append(adminId);
        sb.append(", roleId=").append(roleId);
        sb.append(", eventType=").append(eventType);
        sb.append(", eventTime=").append(eventTime);
        sb.append(", ipAddress=").append(ipAddress);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}