package com.gndc.core.model;

import com.gndc.common.model.BaseEntity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "dc_app_exception")
public class AppException extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_app_exception.id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_app_exception.user_id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_app_exception.session_id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_app_exception.device_and_version
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String deviceAndVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_app_exception.exception
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_app_exception.id
     *
     * @return the value of dc_app_exception.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_app_exception.id
     *
     * @param id the value for dc_app_exception.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_app_exception.user_id
     *
     * @return the value of dc_app_exception.user_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_app_exception.user_id
     *
     * @param userId the value for dc_app_exception.user_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_app_exception.session_id
     *
     * @return the value of dc_app_exception.session_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_app_exception.session_id
     *
     * @param sessionId the value for dc_app_exception.session_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_app_exception.device_and_version
     *
     * @return the value of dc_app_exception.device_and_version
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getDeviceAndVersion() {
        return deviceAndVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_app_exception.device_and_version
     *
     * @param deviceAndVersion the value for dc_app_exception.device_and_version
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setDeviceAndVersion(String deviceAndVersion) {
        this.deviceAndVersion = deviceAndVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_app_exception.exception
     *
     * @return the value of dc_app_exception.exception
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getException() {
        return exception;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_app_exception.exception
     *
     * @param exception the value for dc_app_exception.exception
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setException(String exception) {
        this.exception = exception;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_app_exception
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AppException other = (AppException) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
                && (this.getSessionId() == null ? other.getSessionId() == null : this.getSessionId().equals(other.getSessionId()))
                && (this.getDeviceAndVersion() == null ? other.getDeviceAndVersion() == null : this.getDeviceAndVersion().equals(other.getDeviceAndVersion()))
                && (this.getException() == null ? other.getException() == null : this.getException().equals(other.getException()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_app_exception
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getSessionId() == null) ? 0 : getSessionId().hashCode());
        result = prime * result + ((getDeviceAndVersion() == null) ? 0 : getDeviceAndVersion().hashCode());
        result = prime * result + ((getException() == null) ? 0 : getException().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_app_exception
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", sessionId=").append(sessionId);
        sb.append(", deviceAndVersion=").append(deviceAndVersion);
        sb.append(", exception=").append(exception);
        sb.append("]");
        return sb.toString();
    }
}