package com.gndc.core.model;

import com.gndc.common.model.BaseEntity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "dc_area")
public class Area extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_area.id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_area.name
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_area.pid
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_area.region
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Byte region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_area.first_char
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String firstChar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_area.id
     *
     * @return the value of dc_area.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_area.id
     *
     * @param id the value for dc_area.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_area.name
     *
     * @return the value of dc_area.name
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_area.name
     *
     * @param name the value for dc_area.name
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_area.pid
     *
     * @return the value of dc_area.pid
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_area.pid
     *
     * @param pid the value for dc_area.pid
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_area.region
     *
     * @return the value of dc_area.region
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Byte getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_area.region
     *
     * @param region the value for dc_area.region
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setRegion(Byte region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_area.first_char
     *
     * @return the value of dc_area.first_char
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getFirstChar() {
        return firstChar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_area.first_char
     *
     * @param firstChar the value for dc_area.first_char
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setFirstChar(String firstChar) {
        this.firstChar = firstChar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_area
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Area other = (Area) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
                && (this.getPid() == null ? other.getPid() == null : this.getPid().equals(other.getPid()))
                && (this.getRegion() == null ? other.getRegion() == null : this.getRegion().equals(other.getRegion()))
                && (this.getFirstChar() == null ? other.getFirstChar() == null : this.getFirstChar().equals(other.getFirstChar()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_area
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getPid() == null) ? 0 : getPid().hashCode());
        result = prime * result + ((getRegion() == null) ? 0 : getRegion().hashCode());
        result = prime * result + ((getFirstChar() == null) ? 0 : getFirstChar().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_area
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", pid=").append(pid);
        sb.append(", region=").append(region);
        sb.append(", firstChar=").append(firstChar);
        sb.append("]");
        return sb.toString();
    }
}