package com.gndc.core.model;

import com.gndc.common.model.BaseEntity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@Table(name = "dc_operation_banner")
public class Banner extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_operation_banner.id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_operation_banner.product_id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer productId;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_operation_banner.title
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_operation_banner.status
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_operation_banner.is_del
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Byte isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_operation_banner.position
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Byte position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_operation_banner.link
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_operation_banner.img_url
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_operation_banner.begin_time
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_operation_banner.end_time
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_operation_banner.id
     *
     * @return the value of dc_operation_banner.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_operation_banner.id
     *
     * @param id the value for dc_operation_banner.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_operation_banner.product_id
     *
     * @return the value of dc_operation_banner.product_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_operation_banner.product_id
     *
     * @param productId the value for dc_operation_banner.product_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_operation_banner.title
     *
     * @return the value of dc_operation_banner.title
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_operation_banner.title
     *
     * @param title the value for dc_operation_banner.title
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_operation_banner.status
     *
     * @return the value of dc_operation_banner.status
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_operation_banner.status
     *
     * @param status the value for dc_operation_banner.status
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_operation_banner.is_del
     *
     * @return the value of dc_operation_banner.is_del
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Byte getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_operation_banner.is_del
     *
     * @param isDel the value for dc_operation_banner.is_del
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setIsDel(Byte isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_operation_banner.position
     *
     * @return the value of dc_operation_banner.position
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Byte getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_operation_banner.position
     *
     * @param position the value for dc_operation_banner.position
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setPosition(Byte position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_operation_banner.link
     *
     * @return the value of dc_operation_banner.link
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_operation_banner.link
     *
     * @param link the value for dc_operation_banner.link
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_operation_banner.img_url
     *
     * @return the value of dc_operation_banner.img_url
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_operation_banner.img_url
     *
     * @param imgUrl the value for dc_operation_banner.img_url
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_operation_banner.begin_time
     *
     * @return the value of dc_operation_banner.begin_time
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Date getBeginTime() {
        return beginTime;
    }


    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_operation_banner.begin_time
     *
     * @param beginTime the value for dc_operation_banner.begin_time
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_operation_banner.end_time
     *
     * @return the value of dc_operation_banner.end_time
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_operation_banner.end_time
     *
     * @param endTime the value for dc_operation_banner.end_time
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }


    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table dc_operation_banner
     *
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Banner other = (Banner) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getProductId() == null ? other.getProductId() == null
                : this.getProductId().equals(other.getProductId()))
                && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
                && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
                && (this.getIsDel() == null ? other.getIsDel() == null : this.getIsDel().equals(other.getIsDel()))
                && (this.getPosition() == null ? other.getPosition() == null
                : this.getPosition().equals(other.getPosition()))
                && (this.getLink() == null ? other.getLink() == null : this.getLink().equals(other.getLink()))
                && (this.getImgUrl() == null ? other.getImgUrl() == null : this.getImgUrl().equals(other.getImgUrl()))
                && (this.getBeginTime() == null ? other.getBeginTime() == null
                : this.getBeginTime().equals(other.getBeginTime()))
                && (this.getEndTime() == null ? other.getEndTime() == null
                : this.getEndTime().equals(other.getEndTime()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null
                : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null
                : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table dc_operation_banner
     *
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getIsDel() == null) ? 0 : getIsDel().hashCode());
        result = prime * result + ((getPosition() == null) ? 0 : getPosition().hashCode());
        result = prime * result + ((getLink() == null) ? 0 : getLink().hashCode());
        result = prime * result + ((getImgUrl() == null) ? 0 : getImgUrl().hashCode());
        result = prime * result + ((getBeginTime() == null) ? 0 : getBeginTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table dc_operation_banner
     *
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", title=").append(title);
        sb.append(", status=").append(status);
        sb.append(", isDel=").append(isDel);
        sb.append(", position=").append(position);
        sb.append(", link=").append(link);
        sb.append(", imgUrl=").append(imgUrl);
        sb.append(", beginTime=").append(beginTime);
        sb.append(", endTime=").append(endTime);
        sb.append("]");
        return sb.toString();
    }

}