package com.gndc.core.model;

import com.gndc.common.model.BaseEntity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@Table(name = "dc_product_hot")
public class ProductHot extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_product_hot.id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_product_hot.product_id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_product_hot.product_name
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_product_hot.status
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Byte status;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_product_hot.position
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Byte position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_product_hot.online_time
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Date onlineTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_product_hot.offline_time
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Date offlineTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_product_hot.id
     *
     * @return the value of dc_product_hot.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_product_hot.id
     *
     * @param id the value for dc_product_hot.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_product_hot.product_id
     *
     * @return the value of dc_product_hot.product_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_product_hot.product_id
     *
     * @param productId the value for dc_product_hot.product_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_product_hot.product_name
     *
     * @return the value of dc_product_hot.product_name
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_product_hot.product_name
     *
     * @param productName the value for dc_product_hot.product_name
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_product_hot.status
     *
     * @return the value of dc_product_hot.status
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_product_hot.status
     *
     * @param status the value for dc_product_hot.status
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_product_hot.position
     *
     * @return the value of dc_product_hot.position
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Byte getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_product_hot.position
     *
     * @param position the value for dc_product_hot.position
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setPosition(Byte position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_product_hot.online_time
     *
     * @return the value of dc_product_hot.online_time
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Date getOnlineTime() {
        return onlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_product_hot.online_time
     *
     * @param onlineTime the value for dc_product_hot.online_time
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setOnlineTime(Date onlineTime) {
        this.onlineTime = onlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_product_hot.offline_time
     *
     * @return the value of dc_product_hot.offline_time
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Date getOfflineTime() {
        return offlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_product_hot.offline_time
     *
     * @param offlineTime the value for dc_product_hot.offline_time
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setOfflineTime(Date offlineTime) {
        this.offlineTime = offlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_product_hot
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ProductHot other = (ProductHot) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
                && (this.getProductName() == null ? other.getProductName() == null : this.getProductName().equals(other.getProductName()))
                && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
                && (this.getPosition() == null ? other.getPosition() == null : this.getPosition().equals(other.getPosition()))
                && (this.getOnlineTime() == null ? other.getOnlineTime() == null : this.getOnlineTime().equals(other.getOnlineTime()))
                && (this.getOfflineTime() == null ? other.getOfflineTime() == null : this.getOfflineTime().equals(other.getOfflineTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_product_hot
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getProductName() == null) ? 0 : getProductName().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getPosition() == null) ? 0 : getPosition().hashCode());
        result = prime * result + ((getOnlineTime() == null) ? 0 : getOnlineTime().hashCode());
        result = prime * result + ((getOfflineTime() == null) ? 0 : getOfflineTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_product_hot
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", productName=").append(productName);
        sb.append(", status=").append(status);
        sb.append(", position=").append(position);
        sb.append(", onlineTime=").append(onlineTime);
        sb.append(", offlineTime=").append(offlineTime);
        sb.append("]");
        return sb.toString();
    }
}