package com.gndc.core.model;

import com.gndc.common.model.BaseEntity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "dc_product_interface")
public class ProductInterface extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_product_interface.id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_product_interface.product_id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_product_interface.product_name
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_product_interface.interface_config
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String interfaceConfig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_product_interface.status
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_product_interface.id
     *
     * @return the value of dc_product_interface.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_product_interface.id
     *
     * @param id the value for dc_product_interface.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_product_interface.product_id
     *
     * @return the value of dc_product_interface.product_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_product_interface.product_id
     *
     * @param productId the value for dc_product_interface.product_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_product_interface.product_name
     *
     * @return the value of dc_product_interface.product_name
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_product_interface.product_name
     *
     * @param productName the value for dc_product_interface.product_name
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_product_interface.interface_config
     *
     * @return the value of dc_product_interface.interface_config
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getInterfaceConfig() {
        return interfaceConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_product_interface.interface_config
     *
     * @param interfaceConfig the value for dc_product_interface.interface_config
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setInterfaceConfig(String interfaceConfig) {
        this.interfaceConfig = interfaceConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_product_interface.status
     *
     * @return the value of dc_product_interface.status
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_product_interface.status
     *
     * @param status the value for dc_product_interface.status
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_product_interface
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ProductInterface other = (ProductInterface) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
                && (this.getProductName() == null ? other.getProductName() == null : this.getProductName().equals(other.getProductName()))
                && (this.getInterfaceConfig() == null ? other.getInterfaceConfig() == null : this.getInterfaceConfig().equals(other.getInterfaceConfig()))
                && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_product_interface
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getProductName() == null) ? 0 : getProductName().hashCode());
        result = prime * result + ((getInterfaceConfig() == null) ? 0 : getInterfaceConfig().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_product_interface
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", productName=").append(productName);
        sb.append(", interfaceConfig=").append(interfaceConfig);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}