package com.gndc.core.model;

import com.gndc.common.model.BaseEntity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@Table(name = "dc_product_statistic")
public class ProductStatistic extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_product_statistic.id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_product_statistic.prod_id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer prodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_product_statistic.product_name
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_product_statistic.hot_clicks
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer hotClicks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_product_statistic.list_clicks
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer listClicks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_product_statistic.click_downloads
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer clickDownloads;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_product_statistic.actual_downloads
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer actualDownloads;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_product_statistic.actual_installs
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer actualInstalls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_product_statistic.statistic_date
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Date statisticDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_product_statistic.id
     *
     * @return the value of dc_product_statistic.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_product_statistic.id
     *
     * @param id the value for dc_product_statistic.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_product_statistic.prod_id
     *
     * @return the value of dc_product_statistic.prod_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_product_statistic.prod_id
     *
     * @param prodId the value for dc_product_statistic.prod_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setProdId(Integer prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_product_statistic.product_name
     *
     * @return the value of dc_product_statistic.product_name
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_product_statistic.product_name
     *
     * @param productName the value for dc_product_statistic.product_name
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_product_statistic.hot_clicks
     *
     * @return the value of dc_product_statistic.hot_clicks
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getHotClicks() {
        return hotClicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_product_statistic.hot_clicks
     *
     * @param hotClicks the value for dc_product_statistic.hot_clicks
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setHotClicks(Integer hotClicks) {
        this.hotClicks = hotClicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_product_statistic.list_clicks
     *
     * @return the value of dc_product_statistic.list_clicks
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getListClicks() {
        return listClicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_product_statistic.list_clicks
     *
     * @param listClicks the value for dc_product_statistic.list_clicks
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setListClicks(Integer listClicks) {
        this.listClicks = listClicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_product_statistic.click_downloads
     *
     * @return the value of dc_product_statistic.click_downloads
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getClickDownloads() {
        return clickDownloads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_product_statistic.click_downloads
     *
     * @param clickDownloads the value for dc_product_statistic.click_downloads
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setClickDownloads(Integer clickDownloads) {
        this.clickDownloads = clickDownloads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_product_statistic.actual_downloads
     *
     * @return the value of dc_product_statistic.actual_downloads
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getActualDownloads() {
        return actualDownloads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_product_statistic.actual_downloads
     *
     * @param actualDownloads the value for dc_product_statistic.actual_downloads
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setActualDownloads(Integer actualDownloads) {
        this.actualDownloads = actualDownloads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_product_statistic.actual_installs
     *
     * @return the value of dc_product_statistic.actual_installs
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getActualInstalls() {
        return actualInstalls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_product_statistic.actual_installs
     *
     * @param actualInstalls the value for dc_product_statistic.actual_installs
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setActualInstalls(Integer actualInstalls) {
        this.actualInstalls = actualInstalls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_product_statistic.statistic_date
     *
     * @return the value of dc_product_statistic.statistic_date
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Date getStatisticDate() {
        return statisticDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_product_statistic.statistic_date
     *
     * @param statisticDate the value for dc_product_statistic.statistic_date
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setStatisticDate(Date statisticDate) {
        this.statisticDate = statisticDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_product_statistic
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ProductStatistic other = (ProductStatistic) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getProdId() == null ? other.getProdId() == null : this.getProdId().equals(other.getProdId()))
                && (this.getProductName() == null ? other.getProductName() == null : this.getProductName().equals(other.getProductName()))
                && (this.getHotClicks() == null ? other.getHotClicks() == null : this.getHotClicks().equals(other.getHotClicks()))
                && (this.getListClicks() == null ? other.getListClicks() == null : this.getListClicks().equals(other.getListClicks()))
                && (this.getClickDownloads() == null ? other.getClickDownloads() == null : this.getClickDownloads().equals(other.getClickDownloads()))
                && (this.getActualDownloads() == null ? other.getActualDownloads() == null : this.getActualDownloads().equals(other.getActualDownloads()))
                && (this.getActualInstalls() == null ? other.getActualInstalls() == null : this.getActualInstalls().equals(other.getActualInstalls()))
                && (this.getStatisticDate() == null ? other.getStatisticDate() == null : this.getStatisticDate().equals(other.getStatisticDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_product_statistic
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProdId() == null) ? 0 : getProdId().hashCode());
        result = prime * result + ((getProductName() == null) ? 0 : getProductName().hashCode());
        result = prime * result + ((getHotClicks() == null) ? 0 : getHotClicks().hashCode());
        result = prime * result + ((getListClicks() == null) ? 0 : getListClicks().hashCode());
        result = prime * result + ((getClickDownloads() == null) ? 0 : getClickDownloads().hashCode());
        result = prime * result + ((getActualDownloads() == null) ? 0 : getActualDownloads().hashCode());
        result = prime * result + ((getActualInstalls() == null) ? 0 : getActualInstalls().hashCode());
        result = prime * result + ((getStatisticDate() == null) ? 0 : getStatisticDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_product_statistic
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", prodId=").append(prodId);
        sb.append(", productName=").append(productName);
        sb.append(", hotClicks=").append(hotClicks);
        sb.append(", listClicks=").append(listClicks);
        sb.append(", clickDownloads=").append(clickDownloads);
        sb.append(", actualDownloads=").append(actualDownloads);
        sb.append(", actualInstalls=").append(actualInstalls);
        sb.append(", statisticDate=").append(statisticDate);
        sb.append("]");
        return sb.toString();
    }
}