package com.gndc.core.model;

import com.gndc.common.model.BaseEntity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "dc_role_right")
public class RoleRight extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_role_right.id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_role_right.role_id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_role_right.right_id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer rightId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_role_right.update_admin_id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer updateAdminId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_role_right.id
     *
     * @return the value of dc_role_right.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_role_right.id
     *
     * @param id the value for dc_role_right.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_role_right.role_id
     *
     * @return the value of dc_role_right.role_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_role_right.role_id
     *
     * @param roleId the value for dc_role_right.role_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_role_right.right_id
     *
     * @return the value of dc_role_right.right_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getRightId() {
        return rightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_role_right.right_id
     *
     * @param rightId the value for dc_role_right.right_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setRightId(Integer rightId) {
        this.rightId = rightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_role_right.update_admin_id
     *
     * @return the value of dc_role_right.update_admin_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getUpdateAdminId() {
        return updateAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_role_right.update_admin_id
     *
     * @param updateAdminId the value for dc_role_right.update_admin_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setUpdateAdminId(Integer updateAdminId) {
        this.updateAdminId = updateAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_role_right
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RoleRight other = (RoleRight) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
                && (this.getRightId() == null ? other.getRightId() == null : this.getRightId().equals(other.getRightId()))
                && (this.getUpdateAdminId() == null ? other.getUpdateAdminId() == null : this.getUpdateAdminId().equals(other.getUpdateAdminId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_role_right
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getRightId() == null) ? 0 : getRightId().hashCode());
        result = prime * result + ((getUpdateAdminId() == null) ? 0 : getUpdateAdminId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_role_right
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleId=").append(roleId);
        sb.append(", rightId=").append(rightId);
        sb.append(", updateAdminId=").append(updateAdminId);
        sb.append("]");
        return sb.toString();
    }
}