package com.gndc.core.model;

import com.gndc.common.model.BaseEntity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "dc_sms_log")
public class SmsLog extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_sms_log.id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_sms_log.user_id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_sms_log.mobile
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_sms_log.sms_type
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Byte smsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_sms_log.sms_param
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String smsParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_sms_log.message
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_sms_log.third_channel
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String thirdChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_sms_log.paasoo_phone_val_errcode
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String paasooPhoneValErrcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_sms_log.paasoo_phone_val_format
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String paasooPhoneValFormat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_sms_log.paasoo_phone_val_str
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String paasooPhoneValStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_sms_log.paasoo_sms_messageid
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String paasooSmsMessageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_sms_log.paasoo_sms_status
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String paasooSmsStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_sms_log.paasoo_sms_status_code
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String paasooSmsStatusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_sms_log.paasoo_sms_str
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String paasooSmsStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_sms_log.paasoo_callback_status
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String paasooCallbackStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_sms_log.paasoo_callback_status_code
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String paasooCallbackStatusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_sms_log.paasoo_callback_errcode
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String paasooCallbackErrcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_sms_log.paasoo_callback_str
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String paasooCallbackStr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_sms_log.id
     *
     * @return the value of dc_sms_log.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_sms_log.id
     *
     * @param id the value for dc_sms_log.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_sms_log.user_id
     *
     * @return the value of dc_sms_log.user_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_sms_log.user_id
     *
     * @param userId the value for dc_sms_log.user_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_sms_log.mobile
     *
     * @return the value of dc_sms_log.mobile
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_sms_log.mobile
     *
     * @param mobile the value for dc_sms_log.mobile
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_sms_log.sms_type
     *
     * @return the value of dc_sms_log.sms_type
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Byte getSmsType() {
        return smsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_sms_log.sms_type
     *
     * @param smsType the value for dc_sms_log.sms_type
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setSmsType(Byte smsType) {
        this.smsType = smsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_sms_log.sms_param
     *
     * @return the value of dc_sms_log.sms_param
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getSmsParam() {
        return smsParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_sms_log.sms_param
     *
     * @param smsParam the value for dc_sms_log.sms_param
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setSmsParam(String smsParam) {
        this.smsParam = smsParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_sms_log.message
     *
     * @return the value of dc_sms_log.message
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_sms_log.message
     *
     * @param message the value for dc_sms_log.message
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_sms_log.third_channel
     *
     * @return the value of dc_sms_log.third_channel
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getThirdChannel() {
        return thirdChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_sms_log.third_channel
     *
     * @param thirdChannel the value for dc_sms_log.third_channel
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setThirdChannel(String thirdChannel) {
        this.thirdChannel = thirdChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_sms_log.paasoo_phone_val_errcode
     *
     * @return the value of dc_sms_log.paasoo_phone_val_errcode
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getPaasooPhoneValErrcode() {
        return paasooPhoneValErrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_sms_log.paasoo_phone_val_errcode
     *
     * @param paasooPhoneValErrcode the value for dc_sms_log.paasoo_phone_val_errcode
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setPaasooPhoneValErrcode(String paasooPhoneValErrcode) {
        this.paasooPhoneValErrcode = paasooPhoneValErrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_sms_log.paasoo_phone_val_format
     *
     * @return the value of dc_sms_log.paasoo_phone_val_format
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getPaasooPhoneValFormat() {
        return paasooPhoneValFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_sms_log.paasoo_phone_val_format
     *
     * @param paasooPhoneValFormat the value for dc_sms_log.paasoo_phone_val_format
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setPaasooPhoneValFormat(String paasooPhoneValFormat) {
        this.paasooPhoneValFormat = paasooPhoneValFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_sms_log.paasoo_phone_val_str
     *
     * @return the value of dc_sms_log.paasoo_phone_val_str
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getPaasooPhoneValStr() {
        return paasooPhoneValStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_sms_log.paasoo_phone_val_str
     *
     * @param paasooPhoneValStr the value for dc_sms_log.paasoo_phone_val_str
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setPaasooPhoneValStr(String paasooPhoneValStr) {
        this.paasooPhoneValStr = paasooPhoneValStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_sms_log.paasoo_sms_messageid
     *
     * @return the value of dc_sms_log.paasoo_sms_messageid
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getPaasooSmsMessageid() {
        return paasooSmsMessageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_sms_log.paasoo_sms_messageid
     *
     * @param paasooSmsMessageid the value for dc_sms_log.paasoo_sms_messageid
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setPaasooSmsMessageid(String paasooSmsMessageid) {
        this.paasooSmsMessageid = paasooSmsMessageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_sms_log.paasoo_sms_status
     *
     * @return the value of dc_sms_log.paasoo_sms_status
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getPaasooSmsStatus() {
        return paasooSmsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_sms_log.paasoo_sms_status
     *
     * @param paasooSmsStatus the value for dc_sms_log.paasoo_sms_status
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setPaasooSmsStatus(String paasooSmsStatus) {
        this.paasooSmsStatus = paasooSmsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_sms_log.paasoo_sms_status_code
     *
     * @return the value of dc_sms_log.paasoo_sms_status_code
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getPaasooSmsStatusCode() {
        return paasooSmsStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_sms_log.paasoo_sms_status_code
     *
     * @param paasooSmsStatusCode the value for dc_sms_log.paasoo_sms_status_code
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setPaasooSmsStatusCode(String paasooSmsStatusCode) {
        this.paasooSmsStatusCode = paasooSmsStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_sms_log.paasoo_sms_str
     *
     * @return the value of dc_sms_log.paasoo_sms_str
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getPaasooSmsStr() {
        return paasooSmsStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_sms_log.paasoo_sms_str
     *
     * @param paasooSmsStr the value for dc_sms_log.paasoo_sms_str
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setPaasooSmsStr(String paasooSmsStr) {
        this.paasooSmsStr = paasooSmsStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_sms_log.paasoo_callback_status
     *
     * @return the value of dc_sms_log.paasoo_callback_status
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getPaasooCallbackStatus() {
        return paasooCallbackStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_sms_log.paasoo_callback_status
     *
     * @param paasooCallbackStatus the value for dc_sms_log.paasoo_callback_status
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setPaasooCallbackStatus(String paasooCallbackStatus) {
        this.paasooCallbackStatus = paasooCallbackStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_sms_log.paasoo_callback_status_code
     *
     * @return the value of dc_sms_log.paasoo_callback_status_code
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getPaasooCallbackStatusCode() {
        return paasooCallbackStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_sms_log.paasoo_callback_status_code
     *
     * @param paasooCallbackStatusCode the value for dc_sms_log.paasoo_callback_status_code
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setPaasooCallbackStatusCode(String paasooCallbackStatusCode) {
        this.paasooCallbackStatusCode = paasooCallbackStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_sms_log.paasoo_callback_errcode
     *
     * @return the value of dc_sms_log.paasoo_callback_errcode
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getPaasooCallbackErrcode() {
        return paasooCallbackErrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_sms_log.paasoo_callback_errcode
     *
     * @param paasooCallbackErrcode the value for dc_sms_log.paasoo_callback_errcode
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setPaasooCallbackErrcode(String paasooCallbackErrcode) {
        this.paasooCallbackErrcode = paasooCallbackErrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_sms_log.paasoo_callback_str
     *
     * @return the value of dc_sms_log.paasoo_callback_str
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getPaasooCallbackStr() {
        return paasooCallbackStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_sms_log.paasoo_callback_str
     *
     * @param paasooCallbackStr the value for dc_sms_log.paasoo_callback_str
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setPaasooCallbackStr(String paasooCallbackStr) {
        this.paasooCallbackStr = paasooCallbackStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_sms_log
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SmsLog other = (SmsLog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
                && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
                && (this.getSmsType() == null ? other.getSmsType() == null : this.getSmsType().equals(other.getSmsType()))
                && (this.getSmsParam() == null ? other.getSmsParam() == null : this.getSmsParam().equals(other.getSmsParam()))
                && (this.getMessage() == null ? other.getMessage() == null : this.getMessage().equals(other.getMessage()))
                && (this.getThirdChannel() == null ? other.getThirdChannel() == null : this.getThirdChannel().equals(other.getThirdChannel()))
                && (this.getPaasooPhoneValErrcode() == null ? other.getPaasooPhoneValErrcode() == null : this.getPaasooPhoneValErrcode().equals(other.getPaasooPhoneValErrcode()))
                && (this.getPaasooPhoneValFormat() == null ? other.getPaasooPhoneValFormat() == null : this.getPaasooPhoneValFormat().equals(other.getPaasooPhoneValFormat()))
                && (this.getPaasooPhoneValStr() == null ? other.getPaasooPhoneValStr() == null : this.getPaasooPhoneValStr().equals(other.getPaasooPhoneValStr()))
                && (this.getPaasooSmsMessageid() == null ? other.getPaasooSmsMessageid() == null : this.getPaasooSmsMessageid().equals(other.getPaasooSmsMessageid()))
                && (this.getPaasooSmsStatus() == null ? other.getPaasooSmsStatus() == null : this.getPaasooSmsStatus().equals(other.getPaasooSmsStatus()))
                && (this.getPaasooSmsStatusCode() == null ? other.getPaasooSmsStatusCode() == null : this.getPaasooSmsStatusCode().equals(other.getPaasooSmsStatusCode()))
                && (this.getPaasooSmsStr() == null ? other.getPaasooSmsStr() == null : this.getPaasooSmsStr().equals(other.getPaasooSmsStr()))
                && (this.getPaasooCallbackStatus() == null ? other.getPaasooCallbackStatus() == null : this.getPaasooCallbackStatus().equals(other.getPaasooCallbackStatus()))
                && (this.getPaasooCallbackStatusCode() == null ? other.getPaasooCallbackStatusCode() == null : this.getPaasooCallbackStatusCode().equals(other.getPaasooCallbackStatusCode()))
                && (this.getPaasooCallbackErrcode() == null ? other.getPaasooCallbackErrcode() == null : this.getPaasooCallbackErrcode().equals(other.getPaasooCallbackErrcode()))
                && (this.getPaasooCallbackStr() == null ? other.getPaasooCallbackStr() == null : this.getPaasooCallbackStr().equals(other.getPaasooCallbackStr()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_sms_log
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getSmsType() == null) ? 0 : getSmsType().hashCode());
        result = prime * result + ((getSmsParam() == null) ? 0 : getSmsParam().hashCode());
        result = prime * result + ((getMessage() == null) ? 0 : getMessage().hashCode());
        result = prime * result + ((getThirdChannel() == null) ? 0 : getThirdChannel().hashCode());
        result = prime * result + ((getPaasooPhoneValErrcode() == null) ? 0 : getPaasooPhoneValErrcode().hashCode());
        result = prime * result + ((getPaasooPhoneValFormat() == null) ? 0 : getPaasooPhoneValFormat().hashCode());
        result = prime * result + ((getPaasooPhoneValStr() == null) ? 0 : getPaasooPhoneValStr().hashCode());
        result = prime * result + ((getPaasooSmsMessageid() == null) ? 0 : getPaasooSmsMessageid().hashCode());
        result = prime * result + ((getPaasooSmsStatus() == null) ? 0 : getPaasooSmsStatus().hashCode());
        result = prime * result + ((getPaasooSmsStatusCode() == null) ? 0 : getPaasooSmsStatusCode().hashCode());
        result = prime * result + ((getPaasooSmsStr() == null) ? 0 : getPaasooSmsStr().hashCode());
        result = prime * result + ((getPaasooCallbackStatus() == null) ? 0 : getPaasooCallbackStatus().hashCode());
        result = prime * result + ((getPaasooCallbackStatusCode() == null) ? 0 : getPaasooCallbackStatusCode().hashCode());
        result = prime * result + ((getPaasooCallbackErrcode() == null) ? 0 : getPaasooCallbackErrcode().hashCode());
        result = prime * result + ((getPaasooCallbackStr() == null) ? 0 : getPaasooCallbackStr().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_sms_log
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", mobile=").append(mobile);
        sb.append(", smsType=").append(smsType);
        sb.append(", smsParam=").append(smsParam);
        sb.append(", message=").append(message);
        sb.append(", thirdChannel=").append(thirdChannel);
        sb.append(", paasooPhoneValErrcode=").append(paasooPhoneValErrcode);
        sb.append(", paasooPhoneValFormat=").append(paasooPhoneValFormat);
        sb.append(", paasooPhoneValStr=").append(paasooPhoneValStr);
        sb.append(", paasooSmsMessageid=").append(paasooSmsMessageid);
        sb.append(", paasooSmsStatus=").append(paasooSmsStatus);
        sb.append(", paasooSmsStatusCode=").append(paasooSmsStatusCode);
        sb.append(", paasooSmsStr=").append(paasooSmsStr);
        sb.append(", paasooCallbackStatus=").append(paasooCallbackStatus);
        sb.append(", paasooCallbackStatusCode=").append(paasooCallbackStatusCode);
        sb.append(", paasooCallbackErrcode=").append(paasooCallbackErrcode);
        sb.append(", paasooCallbackStr=").append(paasooCallbackStr);
        sb.append("]");
        return sb.toString();
    }
}