package com.gndc.core.model;

import com.gndc.common.model.BaseEntity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "dc_sys_option")
public class SystemOption extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_system_option.id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_system_option.option_group
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String optionGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_system_option.option_key
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String optionKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_system_option.option_value
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String optionValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_system_option.remark
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_system_option.id
     *
     * @return the value of dc_system_option.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_system_option.id
     *
     * @param id the value for dc_system_option.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_system_option.option_group
     *
     * @return the value of dc_system_option.option_group
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getOptionGroup() {
        return optionGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_system_option.option_group
     *
     * @param optionGroup the value for dc_system_option.option_group
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setOptionGroup(String optionGroup) {
        this.optionGroup = optionGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_system_option.option_key
     *
     * @return the value of dc_system_option.option_key
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getOptionKey() {
        return optionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_system_option.option_key
     *
     * @param optionKey the value for dc_system_option.option_key
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setOptionKey(String optionKey) {
        this.optionKey = optionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_system_option.option_value
     *
     * @return the value of dc_system_option.option_value
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getOptionValue() {
        return optionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_system_option.option_value
     *
     * @param optionValue the value for dc_system_option.option_value
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setOptionValue(String optionValue) {
        this.optionValue = optionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_system_option.remark
     *
     * @return the value of dc_system_option.remark
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_system_option.remark
     *
     * @param remark the value for dc_system_option.remark
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_system_option
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SystemOption other = (SystemOption) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getOptionGroup() == null ? other.getOptionGroup() == null : this.getOptionGroup().equals(other.getOptionGroup()))
                && (this.getOptionKey() == null ? other.getOptionKey() == null : this.getOptionKey().equals(other.getOptionKey()))
                && (this.getOptionValue() == null ? other.getOptionValue() == null : this.getOptionValue().equals(other.getOptionValue()))
                && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_system_option
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOptionGroup() == null) ? 0 : getOptionGroup().hashCode());
        result = prime * result + ((getOptionKey() == null) ? 0 : getOptionKey().hashCode());
        result = prime * result + ((getOptionValue() == null) ? 0 : getOptionValue().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_system_option
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", optionGroup=").append(optionGroup);
        sb.append(", optionKey=").append(optionKey);
        sb.append(", optionValue=").append(optionValue);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}