package com.gndc.core.model;

import com.gndc.common.model.BaseEntity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;
@Table(name = "dc_sys_statistic")
public class SystemStatistic extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_system_statistic.id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_system_statistic.history_user
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer historyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_system_statistic.history_active_user
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer historyActiveUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_system_statistic.history_lost_user
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer historyLostUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_system_statistic.history_downloads
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer historyDownloads;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_system_statistic.history_install
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer historyInstall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_system_statistic.today_new_user
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer todayNewUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_system_statistic.today_active_user
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer todayActiveUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_system_statistic.today_lost_user
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer todayLostUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_system_statistic.today_new_downloads
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer todayNewDownloads;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_system_statistic.today_new_install
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer todayNewInstall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_system_statistic.statistic_date
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Date statisticDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_system_statistic.id
     *
     * @return the value of dc_system_statistic.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_system_statistic.id
     *
     * @param id the value for dc_system_statistic.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_system_statistic.history_user
     *
     * @return the value of dc_system_statistic.history_user
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getHistoryUser() {
        return historyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_system_statistic.history_user
     *
     * @param historyUser the value for dc_system_statistic.history_user
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setHistoryUser(Integer historyUser) {
        this.historyUser = historyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_system_statistic.history_active_user
     *
     * @return the value of dc_system_statistic.history_active_user
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getHistoryActiveUser() {
        return historyActiveUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_system_statistic.history_active_user
     *
     * @param historyActiveUser the value for dc_system_statistic.history_active_user
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setHistoryActiveUser(Integer historyActiveUser) {
        this.historyActiveUser = historyActiveUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_system_statistic.history_lost_user
     *
     * @return the value of dc_system_statistic.history_lost_user
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getHistoryLostUser() {
        return historyLostUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_system_statistic.history_lost_user
     *
     * @param historyLostUser the value for dc_system_statistic.history_lost_user
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setHistoryLostUser(Integer historyLostUser) {
        this.historyLostUser = historyLostUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_system_statistic.history_downloads
     *
     * @return the value of dc_system_statistic.history_downloads
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getHistoryDownloads() {
        return historyDownloads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_system_statistic.history_downloads
     *
     * @param historyDownloads the value for dc_system_statistic.history_downloads
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setHistoryDownloads(Integer historyDownloads) {
        this.historyDownloads = historyDownloads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_system_statistic.history_install
     *
     * @return the value of dc_system_statistic.history_install
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getHistoryInstall() {
        return historyInstall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_system_statistic.history_install
     *
     * @param historyInstall the value for dc_system_statistic.history_install
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setHistoryInstall(Integer historyInstall) {
        this.historyInstall = historyInstall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_system_statistic.today_new_user
     *
     * @return the value of dc_system_statistic.today_new_user
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getTodayNewUser() {
        return todayNewUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_system_statistic.today_new_user
     *
     * @param todayNewUser the value for dc_system_statistic.today_new_user
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setTodayNewUser(Integer todayNewUser) {
        this.todayNewUser = todayNewUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_system_statistic.today_active_user
     *
     * @return the value of dc_system_statistic.today_active_user
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getTodayActiveUser() {
        return todayActiveUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_system_statistic.today_active_user
     *
     * @param todayActiveUser the value for dc_system_statistic.today_active_user
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setTodayActiveUser(Integer todayActiveUser) {
        this.todayActiveUser = todayActiveUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_system_statistic.today_lost_user
     *
     * @return the value of dc_system_statistic.today_lost_user
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getTodayLostUser() {
        return todayLostUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_system_statistic.today_lost_user
     *
     * @param todayLostUser the value for dc_system_statistic.today_lost_user
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setTodayLostUser(Integer todayLostUser) {
        this.todayLostUser = todayLostUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_system_statistic.today_new_downloads
     *
     * @return the value of dc_system_statistic.today_new_downloads
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getTodayNewDownloads() {
        return todayNewDownloads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_system_statistic.today_new_downloads
     *
     * @param todayNewDownloads the value for dc_system_statistic.today_new_downloads
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setTodayNewDownloads(Integer todayNewDownloads) {
        this.todayNewDownloads = todayNewDownloads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_system_statistic.today_new_install
     *
     * @return the value of dc_system_statistic.today_new_install
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getTodayNewInstall() {
        return todayNewInstall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_system_statistic.today_new_install
     *
     * @param todayNewInstall the value for dc_system_statistic.today_new_install
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setTodayNewInstall(Integer todayNewInstall) {
        this.todayNewInstall = todayNewInstall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_system_statistic.statistic_date
     *
     * @return the value of dc_system_statistic.statistic_date
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Date getStatisticDate() {
        return statisticDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_system_statistic.statistic_date
     *
     * @param statisticDate the value for dc_system_statistic.statistic_date
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setStatisticDate(Date statisticDate) {
        this.statisticDate = statisticDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_system_statistic
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SystemStatistic other = (SystemStatistic) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getHistoryUser() == null ? other.getHistoryUser() == null : this.getHistoryUser().equals(other.getHistoryUser()))
                && (this.getHistoryActiveUser() == null ? other.getHistoryActiveUser() == null : this.getHistoryActiveUser().equals(other.getHistoryActiveUser()))
                && (this.getHistoryLostUser() == null ? other.getHistoryLostUser() == null : this.getHistoryLostUser().equals(other.getHistoryLostUser()))
                && (this.getHistoryDownloads() == null ? other.getHistoryDownloads() == null : this.getHistoryDownloads().equals(other.getHistoryDownloads()))
                && (this.getHistoryInstall() == null ? other.getHistoryInstall() == null : this.getHistoryInstall().equals(other.getHistoryInstall()))
                && (this.getTodayNewUser() == null ? other.getTodayNewUser() == null : this.getTodayNewUser().equals(other.getTodayNewUser()))
                && (this.getTodayActiveUser() == null ? other.getTodayActiveUser() == null : this.getTodayActiveUser().equals(other.getTodayActiveUser()))
                && (this.getTodayLostUser() == null ? other.getTodayLostUser() == null : this.getTodayLostUser().equals(other.getTodayLostUser()))
                && (this.getTodayNewDownloads() == null ? other.getTodayNewDownloads() == null : this.getTodayNewDownloads().equals(other.getTodayNewDownloads()))
                && (this.getTodayNewInstall() == null ? other.getTodayNewInstall() == null : this.getTodayNewInstall().equals(other.getTodayNewInstall()))
                && (this.getStatisticDate() == null ? other.getStatisticDate() == null : this.getStatisticDate().equals(other.getStatisticDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_system_statistic
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getHistoryUser() == null) ? 0 : getHistoryUser().hashCode());
        result = prime * result + ((getHistoryActiveUser() == null) ? 0 : getHistoryActiveUser().hashCode());
        result = prime * result + ((getHistoryLostUser() == null) ? 0 : getHistoryLostUser().hashCode());
        result = prime * result + ((getHistoryDownloads() == null) ? 0 : getHistoryDownloads().hashCode());
        result = prime * result + ((getHistoryInstall() == null) ? 0 : getHistoryInstall().hashCode());
        result = prime * result + ((getTodayNewUser() == null) ? 0 : getTodayNewUser().hashCode());
        result = prime * result + ((getTodayActiveUser() == null) ? 0 : getTodayActiveUser().hashCode());
        result = prime * result + ((getTodayLostUser() == null) ? 0 : getTodayLostUser().hashCode());
        result = prime * result + ((getTodayNewDownloads() == null) ? 0 : getTodayNewDownloads().hashCode());
        result = prime * result + ((getTodayNewInstall() == null) ? 0 : getTodayNewInstall().hashCode());
        result = prime * result + ((getStatisticDate() == null) ? 0 : getStatisticDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_system_statistic
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", historyUser=").append(historyUser);
        sb.append(", historyActiveUser=").append(historyActiveUser);
        sb.append(", historyLostUser=").append(historyLostUser);
        sb.append(", historyDownloads=").append(historyDownloads);
        sb.append(", historyInstall=").append(historyInstall);
        sb.append(", todayNewUser=").append(todayNewUser);
        sb.append(", todayActiveUser=").append(todayActiveUser);
        sb.append(", todayLostUser=").append(todayLostUser);
        sb.append(", todayNewDownloads=").append(todayNewDownloads);
        sb.append(", todayNewInstall=").append(todayNewInstall);
        sb.append(", statisticDate=").append(statisticDate);
        sb.append("]");
        return sb.toString();
    }
}