package com.gndc.core.model;

import com.gndc.common.model.BaseEntity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "dc_call_record")
public class UserCallRecord extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user_call_record.id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user_call_record.user_phone
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user_call_record.user_id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user_call_record.user_name
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user_call_record.service_id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user_call_record.service_name
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String serviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user_call_record.question
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user_call_record.answer
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user_call_record.is_solve
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Byte isSolve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user_call_record.remark
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user_call_record.id
     *
     * @return the value of dc_user_call_record.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user_call_record.id
     *
     * @param id the value for dc_user_call_record.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user_call_record.user_phone
     *
     * @return the value of dc_user_call_record.user_phone
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user_call_record.user_phone
     *
     * @param userPhone the value for dc_user_call_record.user_phone
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user_call_record.user_id
     *
     * @return the value of dc_user_call_record.user_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user_call_record.user_id
     *
     * @param userId the value for dc_user_call_record.user_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user_call_record.user_name
     *
     * @return the value of dc_user_call_record.user_name
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user_call_record.user_name
     *
     * @param userName the value for dc_user_call_record.user_name
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user_call_record.service_id
     *
     * @return the value of dc_user_call_record.service_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user_call_record.service_id
     *
     * @param serviceId the value for dc_user_call_record.service_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user_call_record.service_name
     *
     * @return the value of dc_user_call_record.service_name
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user_call_record.service_name
     *
     * @param serviceName the value for dc_user_call_record.service_name
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user_call_record.question
     *
     * @return the value of dc_user_call_record.question
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user_call_record.question
     *
     * @param question the value for dc_user_call_record.question
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setQuestion(String question) {
        this.question = question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user_call_record.answer
     *
     * @return the value of dc_user_call_record.answer
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user_call_record.answer
     *
     * @param answer the value for dc_user_call_record.answer
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user_call_record.is_solve
     *
     * @return the value of dc_user_call_record.is_solve
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Byte getIsSolve() {
        return isSolve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user_call_record.is_solve
     *
     * @param isSolve the value for dc_user_call_record.is_solve
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setIsSolve(Byte isSolve) {
        this.isSolve = isSolve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user_call_record.remark
     *
     * @return the value of dc_user_call_record.remark
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user_call_record.remark
     *
     * @param remark the value for dc_user_call_record.remark
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user_call_record
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserCallRecord other = (UserCallRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getUserPhone() == null ? other.getUserPhone() == null : this.getUserPhone().equals(other.getUserPhone()))
                && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
                && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
                && (this.getServiceId() == null ? other.getServiceId() == null : this.getServiceId().equals(other.getServiceId()))
                && (this.getServiceName() == null ? other.getServiceName() == null : this.getServiceName().equals(other.getServiceName()))
                && (this.getQuestion() == null ? other.getQuestion() == null : this.getQuestion().equals(other.getQuestion()))
                && (this.getAnswer() == null ? other.getAnswer() == null : this.getAnswer().equals(other.getAnswer()))
                && (this.getIsSolve() == null ? other.getIsSolve() == null : this.getIsSolve().equals(other.getIsSolve()))
                && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user_call_record
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserPhone() == null) ? 0 : getUserPhone().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getServiceId() == null) ? 0 : getServiceId().hashCode());
        result = prime * result + ((getServiceName() == null) ? 0 : getServiceName().hashCode());
        result = prime * result + ((getQuestion() == null) ? 0 : getQuestion().hashCode());
        result = prime * result + ((getAnswer() == null) ? 0 : getAnswer().hashCode());
        result = prime * result + ((getIsSolve() == null) ? 0 : getIsSolve().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user_call_record
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userPhone=").append(userPhone);
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", serviceId=").append(serviceId);
        sb.append(", serviceName=").append(serviceName);
        sb.append(", question=").append(question);
        sb.append(", answer=").append(answer);
        sb.append(", isSolve=").append(isSolve);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }

}