package com.gndc.core.model;

import com.gndc.common.model.BaseEntity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@Table(name = "dc_user_feedback")
public class UserFeedback extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user_feedback.id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user_feedback.user_id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user_feedback.user_phone
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user_feedback.content
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user_feedback.admin_id
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user_feedback.reply_time
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Date replyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user_feedback.reply_content
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String replyContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user_feedback.status
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user_feedback.picture_url
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    private String pictureUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user_feedback.id
     *
     * @return the value of dc_user_feedback.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user_feedback.id
     *
     * @param id the value for dc_user_feedback.id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user_feedback.user_id
     *
     * @return the value of dc_user_feedback.user_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user_feedback.user_id
     *
     * @param userId the value for dc_user_feedback.user_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user_feedback.user_phone
     *
     * @return the value of dc_user_feedback.user_phone
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user_feedback.user_phone
     *
     * @param userPhone the value for dc_user_feedback.user_phone
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user_feedback.content
     *
     * @return the value of dc_user_feedback.content
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user_feedback.content
     *
     * @param content the value for dc_user_feedback.content
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user_feedback.admin_id
     *
     * @return the value of dc_user_feedback.admin_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user_feedback.admin_id
     *
     * @param adminId the value for dc_user_feedback.admin_id
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user_feedback.reply_time
     *
     * @return the value of dc_user_feedback.reply_time
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Date getReplyTime() {
        return replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user_feedback.reply_time
     *
     * @param replyTime the value for dc_user_feedback.reply_time
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setReplyTime(Date replyTime) {
        this.replyTime = replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user_feedback.reply_content
     *
     * @return the value of dc_user_feedback.reply_content
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getReplyContent() {
        return replyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user_feedback.reply_content
     *
     * @param replyContent the value for dc_user_feedback.reply_content
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user_feedback.status
     *
     * @return the value of dc_user_feedback.status
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user_feedback.status
     *
     * @param status the value for dc_user_feedback.status
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user_feedback.picture_url
     *
     * @return the value of dc_user_feedback.picture_url
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user_feedback.picture_url
     *
     * @param pictureUrl the value for dc_user_feedback.picture_url
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user_feedback
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserFeedback other = (UserFeedback) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
                && (this.getUserPhone() == null ? other.getUserPhone() == null : this.getUserPhone().equals(other.getUserPhone()))
                && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
                && (this.getAdminId() == null ? other.getAdminId() == null : this.getAdminId().equals(other.getAdminId()))
                && (this.getReplyTime() == null ? other.getReplyTime() == null : this.getReplyTime().equals(other.getReplyTime()))
                && (this.getReplyContent() == null ? other.getReplyContent() == null : this.getReplyContent().equals(other.getReplyContent()))
                && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
                && (this.getPictureUrl() == null ? other.getPictureUrl() == null : this.getPictureUrl().equals(other.getPictureUrl()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user_feedback
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserPhone() == null) ? 0 : getUserPhone().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getAdminId() == null) ? 0 : getAdminId().hashCode());
        result = prime * result + ((getReplyTime() == null) ? 0 : getReplyTime().hashCode());
        result = prime * result + ((getReplyContent() == null) ? 0 : getReplyContent().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getPictureUrl() == null) ? 0 : getPictureUrl().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user_feedback
     *
     * @mbggenerated Sat Aug 18 18:25:21 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", userPhone=").append(userPhone);
        sb.append(", content=").append(content);
        sb.append(", adminId=").append(adminId);
        sb.append(", replyTime=").append(replyTime);
        sb.append(", replyContent=").append(replyContent);
        sb.append(", status=").append(status);
        sb.append(", pictureUrl=").append(pictureUrl);
        sb.append("]");
        return sb.toString();
    }
}