package com.gndc.core.model;

import com.gndc.common.model.BaseEntity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import java.math.BigDecimal;
import java.util.Date;
@Table(name = "dc_user")
public class User extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.id
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.phone
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.uid
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.facebook_acc
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String facebookAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.fb_user_name
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String fbUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.fb_accountkit_id
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String fbAccountkitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.whatsapp_acc
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String whatsappAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.name
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.password
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.password_sign
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String passwordSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.area_id
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.head_photo
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String headPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.sex
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.birthday
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.province_id
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.city_id
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.education
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.job
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.income
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private BigDecimal income;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.collection_quantity
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Short collectionQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.reg_channel
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String regChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.reg_device
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Byte regDevice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.reg_time
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Date regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.reg_devicetoken
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String regDevicetoken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.reg_term_type
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String regTermType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.imei
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String imei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.last_login_time
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.last_login_ip
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String lastLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.last_login_device
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Byte lastLoginDevice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.last_login_devicetoken
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String lastLoginDevicetoken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.last_logout_time
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Date lastLogoutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.status
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.remark
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.app_name
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.app_package
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String appPackage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.id
     *
     * @return the value of dc_user.id
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.id
     *
     * @param id the value for dc_user.id
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.phone
     *
     * @return the value of dc_user.phone
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.phone
     *
     * @param phone the value for dc_user.phone
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.uid
     *
     * @return the value of dc_user.uid
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.uid
     *
     * @param uid the value for dc_user.uid
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.facebook_acc
     *
     * @return the value of dc_user.facebook_acc
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public String getFacebookAcc() {
        return facebookAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.facebook_acc
     *
     * @param facebookAcc the value for dc_user.facebook_acc
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setFacebookAcc(String facebookAcc) {
        this.facebookAcc = facebookAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.fb_user_name
     *
     * @return the value of dc_user.fb_user_name
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public String getFbUserName() {
        return fbUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.fb_user_name
     *
     * @param fbUserName the value for dc_user.fb_user_name
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setFbUserName(String fbUserName) {
        this.fbUserName = fbUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.fb_accountkit_id
     *
     * @return the value of dc_user.fb_accountkit_id
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public String getFbAccountkitId() {
        return fbAccountkitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.fb_accountkit_id
     *
     * @param fbAccountkitId the value for dc_user.fb_accountkit_id
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setFbAccountkitId(String fbAccountkitId) {
        this.fbAccountkitId = fbAccountkitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.whatsapp_acc
     *
     * @return the value of dc_user.whatsapp_acc
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public String getWhatsappAcc() {
        return whatsappAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.whatsapp_acc
     *
     * @param whatsappAcc the value for dc_user.whatsapp_acc
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setWhatsappAcc(String whatsappAcc) {
        this.whatsappAcc = whatsappAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.name
     *
     * @return the value of dc_user.name
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.name
     *
     * @param name the value for dc_user.name
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.password
     *
     * @return the value of dc_user.password
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.password
     *
     * @param password the value for dc_user.password
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.password_sign
     *
     * @return the value of dc_user.password_sign
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public String getPasswordSign() {
        return passwordSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.password_sign
     *
     * @param passwordSign the value for dc_user.password_sign
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setPasswordSign(String passwordSign) {
        this.passwordSign = passwordSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.area_id
     *
     * @return the value of dc_user.area_id
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.area_id
     *
     * @param areaId the value for dc_user.area_id
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.head_photo
     *
     * @return the value of dc_user.head_photo
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public String getHeadPhoto() {
        return headPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.head_photo
     *
     * @param headPhoto the value for dc_user.head_photo
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setHeadPhoto(String headPhoto) {
        this.headPhoto = headPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.sex
     *
     * @return the value of dc_user.sex
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.sex
     *
     * @param sex the value for dc_user.sex
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.birthday
     *
     * @return the value of dc_user.birthday
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.birthday
     *
     * @param birthday the value for dc_user.birthday
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.province_id
     *
     * @return the value of dc_user.province_id
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.province_id
     *
     * @param provinceId the value for dc_user.province_id
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.city_id
     *
     * @return the value of dc_user.city_id
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.city_id
     *
     * @param cityId the value for dc_user.city_id
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.education
     *
     * @return the value of dc_user.education
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.education
     *
     * @param education the value for dc_user.education
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setEducation(String education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.job
     *
     * @return the value of dc_user.job
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.job
     *
     * @param job the value for dc_user.job
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setJob(String job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.income
     *
     * @return the value of dc_user.income
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public BigDecimal getIncome() {
        return income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.income
     *
     * @param income the value for dc_user.income
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setIncome(BigDecimal income) {
        this.income = income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.collection_quantity
     *
     * @return the value of dc_user.collection_quantity
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public Short getCollectionQuantity() {
        return collectionQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.collection_quantity
     *
     * @param collectionQuantity the value for dc_user.collection_quantity
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setCollectionQuantity(Short collectionQuantity) {
        this.collectionQuantity = collectionQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.reg_channel
     *
     * @return the value of dc_user.reg_channel
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public String getRegChannel() {
        return regChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.reg_channel
     *
     * @param regChannel the value for dc_user.reg_channel
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setRegChannel(String regChannel) {
        this.regChannel = regChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.reg_device
     *
     * @return the value of dc_user.reg_device
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public Byte getRegDevice() {
        return regDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.reg_device
     *
     * @param regDevice the value for dc_user.reg_device
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setRegDevice(Byte regDevice) {
        this.regDevice = regDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.reg_time
     *
     * @return the value of dc_user.reg_time
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.reg_time
     *
     * @param regTime the value for dc_user.reg_time
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.reg_devicetoken
     *
     * @return the value of dc_user.reg_devicetoken
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public String getRegDevicetoken() {
        return regDevicetoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.reg_devicetoken
     *
     * @param regDevicetoken the value for dc_user.reg_devicetoken
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setRegDevicetoken(String regDevicetoken) {
        this.regDevicetoken = regDevicetoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.reg_term_type
     *
     * @return the value of dc_user.reg_term_type
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public String getRegTermType() {
        return regTermType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.reg_term_type
     *
     * @param regTermType the value for dc_user.reg_term_type
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setRegTermType(String regTermType) {
        this.regTermType = regTermType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.imei
     *
     * @return the value of dc_user.imei
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.imei
     *
     * @param imei the value for dc_user.imei
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.last_login_time
     *
     * @return the value of dc_user.last_login_time
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.last_login_time
     *
     * @param lastLoginTime the value for dc_user.last_login_time
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.last_login_ip
     *
     * @return the value of dc_user.last_login_ip
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.last_login_ip
     *
     * @param lastLoginIp the value for dc_user.last_login_ip
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.last_login_device
     *
     * @return the value of dc_user.last_login_device
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public Byte getLastLoginDevice() {
        return lastLoginDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.last_login_device
     *
     * @param lastLoginDevice the value for dc_user.last_login_device
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setLastLoginDevice(Byte lastLoginDevice) {
        this.lastLoginDevice = lastLoginDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.last_login_devicetoken
     *
     * @return the value of dc_user.last_login_devicetoken
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public String getLastLoginDevicetoken() {
        return lastLoginDevicetoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.last_login_devicetoken
     *
     * @param lastLoginDevicetoken the value for dc_user.last_login_devicetoken
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setLastLoginDevicetoken(String lastLoginDevicetoken) {
        this.lastLoginDevicetoken = lastLoginDevicetoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.last_logout_time
     *
     * @return the value of dc_user.last_logout_time
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public Date getLastLogoutTime() {
        return lastLogoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.last_logout_time
     *
     * @param lastLogoutTime the value for dc_user.last_logout_time
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setLastLogoutTime(Date lastLogoutTime) {
        this.lastLogoutTime = lastLogoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.status
     *
     * @return the value of dc_user.status
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.status
     *
     * @param status the value for dc_user.status
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.remark
     *
     * @return the value of dc_user.remark
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.remark
     *
     * @param remark the value for dc_user.remark
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.app_name
     *
     * @return the value of dc_user.app_name
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.app_name
     *
     * @param appName the value for dc_user.app_name
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_user.app_package
     *
     * @return the value of dc_user.app_package
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public String getAppPackage() {
        return appPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_user.app_package
     *
     * @param appPackage the value for dc_user.app_package
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    public void setAppPackage(String appPackage) {
        this.appPackage = appPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
                && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
                && (this.getFacebookAcc() == null ? other.getFacebookAcc() == null : this.getFacebookAcc().equals(other.getFacebookAcc()))
                && (this.getFbUserName() == null ? other.getFbUserName() == null : this.getFbUserName().equals(other.getFbUserName()))
                && (this.getFbAccountkitId() == null ? other.getFbAccountkitId() == null : this.getFbAccountkitId().equals(other.getFbAccountkitId()))
                && (this.getWhatsappAcc() == null ? other.getWhatsappAcc() == null : this.getWhatsappAcc().equals(other.getWhatsappAcc()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
                && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
                && (this.getPasswordSign() == null ? other.getPasswordSign() == null : this.getPasswordSign().equals(other.getPasswordSign()))
                && (this.getAreaId() == null ? other.getAreaId() == null : this.getAreaId().equals(other.getAreaId()))
                && (this.getHeadPhoto() == null ? other.getHeadPhoto() == null : this.getHeadPhoto().equals(other.getHeadPhoto()))
                && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
                && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
                && (this.getProvinceId() == null ? other.getProvinceId() == null : this.getProvinceId().equals(other.getProvinceId()))
                && (this.getCityId() == null ? other.getCityId() == null : this.getCityId().equals(other.getCityId()))
                && (this.getEducation() == null ? other.getEducation() == null : this.getEducation().equals(other.getEducation()))
                && (this.getJob() == null ? other.getJob() == null : this.getJob().equals(other.getJob()))
                && (this.getIncome() == null ? other.getIncome() == null : this.getIncome().equals(other.getIncome()))
                && (this.getCollectionQuantity() == null ? other.getCollectionQuantity() == null : this.getCollectionQuantity().equals(other.getCollectionQuantity()))
                && (this.getRegChannel() == null ? other.getRegChannel() == null : this.getRegChannel().equals(other.getRegChannel()))
                && (this.getRegDevice() == null ? other.getRegDevice() == null : this.getRegDevice().equals(other.getRegDevice()))
                && (this.getRegTime() == null ? other.getRegTime() == null : this.getRegTime().equals(other.getRegTime()))
                && (this.getRegDevicetoken() == null ? other.getRegDevicetoken() == null : this.getRegDevicetoken().equals(other.getRegDevicetoken()))
                && (this.getRegTermType() == null ? other.getRegTermType() == null : this.getRegTermType().equals(other.getRegTermType()))
                && (this.getImei() == null ? other.getImei() == null : this.getImei().equals(other.getImei()))
                && (this.getLastLoginTime() == null ? other.getLastLoginTime() == null : this.getLastLoginTime().equals(other.getLastLoginTime()))
                && (this.getLastLoginIp() == null ? other.getLastLoginIp() == null : this.getLastLoginIp().equals(other.getLastLoginIp()))
                && (this.getLastLoginDevice() == null ? other.getLastLoginDevice() == null : this.getLastLoginDevice().equals(other.getLastLoginDevice()))
                && (this.getLastLoginDevicetoken() == null ? other.getLastLoginDevicetoken() == null : this.getLastLoginDevicetoken().equals(other.getLastLoginDevicetoken()))
                && (this.getLastLogoutTime() == null ? other.getLastLogoutTime() == null : this.getLastLogoutTime().equals(other.getLastLogoutTime()))
                && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
                && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
                && (this.getAppName() == null ? other.getAppName() == null : this.getAppName().equals(other.getAppName()))
                && (this.getAppPackage() == null ? other.getAppPackage() == null : this.getAppPackage().equals(other.getAppPackage()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getFacebookAcc() == null) ? 0 : getFacebookAcc().hashCode());
        result = prime * result + ((getFbUserName() == null) ? 0 : getFbUserName().hashCode());
        result = prime * result + ((getFbAccountkitId() == null) ? 0 : getFbAccountkitId().hashCode());
        result = prime * result + ((getWhatsappAcc() == null) ? 0 : getWhatsappAcc().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getPasswordSign() == null) ? 0 : getPasswordSign().hashCode());
        result = prime * result + ((getAreaId() == null) ? 0 : getAreaId().hashCode());
        result = prime * result + ((getHeadPhoto() == null) ? 0 : getHeadPhoto().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getProvinceId() == null) ? 0 : getProvinceId().hashCode());
        result = prime * result + ((getCityId() == null) ? 0 : getCityId().hashCode());
        result = prime * result + ((getEducation() == null) ? 0 : getEducation().hashCode());
        result = prime * result + ((getJob() == null) ? 0 : getJob().hashCode());
        result = prime * result + ((getIncome() == null) ? 0 : getIncome().hashCode());
        result = prime * result + ((getCollectionQuantity() == null) ? 0 : getCollectionQuantity().hashCode());
        result = prime * result + ((getRegChannel() == null) ? 0 : getRegChannel().hashCode());
        result = prime * result + ((getRegDevice() == null) ? 0 : getRegDevice().hashCode());
        result = prime * result + ((getRegTime() == null) ? 0 : getRegTime().hashCode());
        result = prime * result + ((getRegDevicetoken() == null) ? 0 : getRegDevicetoken().hashCode());
        result = prime * result + ((getRegTermType() == null) ? 0 : getRegTermType().hashCode());
        result = prime * result + ((getImei() == null) ? 0 : getImei().hashCode());
        result = prime * result + ((getLastLoginTime() == null) ? 0 : getLastLoginTime().hashCode());
        result = prime * result + ((getLastLoginIp() == null) ? 0 : getLastLoginIp().hashCode());
        result = prime * result + ((getLastLoginDevice() == null) ? 0 : getLastLoginDevice().hashCode());
        result = prime * result + ((getLastLoginDevicetoken() == null) ? 0 : getLastLoginDevicetoken().hashCode());
        result = prime * result + ((getLastLogoutTime() == null) ? 0 : getLastLogoutTime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getAppName() == null) ? 0 : getAppName().hashCode());
        result = prime * result + ((getAppPackage() == null) ? 0 : getAppPackage().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_user
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", phone=").append(phone);
        sb.append(", uid=").append(uid);
        sb.append(", facebookAcc=").append(facebookAcc);
        sb.append(", fbUserName=").append(fbUserName);
        sb.append(", fbAccountkitId=").append(fbAccountkitId);
        sb.append(", whatsappAcc=").append(whatsappAcc);
        sb.append(", name=").append(name);
        sb.append(", password=").append(password);
        sb.append(", passwordSign=").append(passwordSign);
        sb.append(", areaId=").append(areaId);
        sb.append(", headPhoto=").append(headPhoto);
        sb.append(", sex=").append(sex);
        sb.append(", birthday=").append(birthday);
        sb.append(", provinceId=").append(provinceId);
        sb.append(", cityId=").append(cityId);
        sb.append(", education=").append(education);
        sb.append(", job=").append(job);
        sb.append(", income=").append(income);
        sb.append(", collectionQuantity=").append(collectionQuantity);
        sb.append(", regChannel=").append(regChannel);
        sb.append(", regDevice=").append(regDevice);
        sb.append(", regTime=").append(regTime);
        sb.append(", regDevicetoken=").append(regDevicetoken);
        sb.append(", regTermType=").append(regTermType);
        sb.append(", imei=").append(imei);
        sb.append(", lastLoginTime=").append(lastLoginTime);
        sb.append(", lastLoginIp=").append(lastLoginIp);
        sb.append(", lastLoginDevice=").append(lastLoginDevice);
        sb.append(", lastLoginDevicetoken=").append(lastLoginDevicetoken);
        sb.append(", lastLogoutTime=").append(lastLogoutTime);
        sb.append(", status=").append(status);
        sb.append(", remark=").append(remark);
        sb.append(", appName=").append(appName);
        sb.append(", appPackage=").append(appPackage);
        sb.append("]");
        return sb.toString();
    }
}