package com.gndc.common.model;

import com.gndc.common.utils.DateUtil;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

@Getter
@Setter
public class Admin implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.id
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.oper_id
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private Integer operId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.name
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.login_name
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.email
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.password
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.password_sign
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private String passwordSign;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.operate_sign
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private String operateSign;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.is_lock
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private Byte isLock;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.lock_time
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private Date lockTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.login_count
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private Integer loginCount;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.last_login_time
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.last_login_ip
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private String lastLoginIp;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.last_logout_time
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private Date lastLogoutTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.telephone
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.phone
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.level
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private Byte level;

    private Integer partnerId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.role_id
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.status
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.create_admin_id
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private Integer createAdminId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.update_admin_id
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private Integer updateAdminId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.create_time
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_admin.update_time
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    private Date updateTime;

    /**
     * 冗余字段
     */
    private List<Right> rightList;

    private String RoleName;

    /**
     * @return roleName
     */
    public String getRoleName() {
        return RoleName;
    }

    /**
     * @param roleName 要设置的 roleName
     */
    public void setRoleName(String roleName) {
        RoleName = roleName;
    }

    /**
     * @return rightList
     */
    public List<Right> getRightList() {
        return rightList;
    }

    /**
     * @param rightList 要设置的 rightList
     */
    public void setRightList(List<Right> rightList) {
        this.rightList = rightList;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.id
     *
     * @return the value of dc_admin.id
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.id
     *
     * @param id the value for dc_admin.id
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.oper_id
     *
     * @return the value of dc_admin.oper_id
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public Integer getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.oper_id
     *
     * @param operId the value for dc_admin.oper_id
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setOperId(Integer operId) {
        this.operId = operId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.name
     *
     * @return the value of dc_admin.name
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.name
     *
     * @param name the value for dc_admin.name
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.login_name
     *
     * @return the value of dc_admin.login_name
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.login_name
     *
     * @param loginName the value for dc_admin.login_name
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.email
     *
     * @return the value of dc_admin.email
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.email
     *
     * @param email the value for dc_admin.email
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.password
     *
     * @return the value of dc_admin.password
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.password
     *
     * @param password the value for dc_admin.password
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.password_sign
     *
     * @return the value of dc_admin.password_sign
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public String getPasswordSign() {
        return passwordSign;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.password_sign
     *
     * @param passwordSign the value for dc_admin.password_sign
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setPasswordSign(String passwordSign) {
        this.passwordSign = passwordSign;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.operate_sign
     *
     * @return the value of dc_admin.operate_sign
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public String getOperateSign() {
        return operateSign;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.operate_sign
     *
     * @param operateSign the value for dc_admin.operate_sign
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setOperateSign(String operateSign) {
        this.operateSign = operateSign;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.is_lock
     *
     * @return the value of dc_admin.is_lock
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public Byte getIsLock() {
        return isLock;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.is_lock
     *
     * @param isLock the value for dc_admin.is_lock
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setIsLock(Byte isLock) {
        this.isLock = isLock;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.lock_time
     *
     * @return the value of dc_admin.lock_time
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public Date getLockTime() {
        return lockTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.lock_time
     *
     * @param lockTime the value for dc_admin.lock_time
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setLockTime(Date lockTime) {
        this.lockTime = lockTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.login_count
     *
     * @return the value of dc_admin.login_count
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.login_count
     *
     * @param loginCount the value for dc_admin.login_count
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.last_login_time
     *
     * @return the value of dc_admin.last_login_time
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.last_login_time
     *
     * @param lastLoginTime the value for dc_admin.last_login_time
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.last_login_ip
     *
     * @return the value of dc_admin.last_login_ip
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.last_login_ip
     *
     * @param lastLoginIp the value for dc_admin.last_login_ip
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.last_logout_time
     *
     * @return the value of dc_admin.last_logout_time
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public Date getLastLogoutTime() {
        return lastLogoutTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.last_logout_time
     *
     * @param lastLogoutTime the value for dc_admin.last_logout_time
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setLastLogoutTime(Date lastLogoutTime) {
        this.lastLogoutTime = lastLogoutTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.telephone
     *
     * @return the value of dc_admin.telephone
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.telephone
     *
     * @param telephone the value for dc_admin.telephone
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.phone
     *
     * @return the value of dc_admin.phone
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.phone
     *
     * @param phone the value for dc_admin.phone
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.level
     *
     * @return the value of dc_admin.level
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.level
     *
     * @param level the value for dc_admin.level
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.role_id
     *
     * @return the value of dc_admin.role_id
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.role_id
     *
     * @param roleId the value for dc_admin.role_id
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.status
     *
     * @return the value of dc_admin.status
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.status
     *
     * @param status the value for dc_admin.status
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.create_admin_id
     *
     * @return the value of dc_admin.create_admin_id
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public Integer getCreateAdminId() {
        return createAdminId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.create_admin_id
     *
     * @param createAdminId the value for dc_admin.create_admin_id
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setCreateAdminId(Integer createAdminId) {
        this.createAdminId = createAdminId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.update_admin_id
     *
     * @return the value of dc_admin.update_admin_id
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public Integer getUpdateAdminId() {
        return updateAdminId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.update_admin_id
     *
     * @param updateAdminId the value for dc_admin.update_admin_id
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setUpdateAdminId(Integer updateAdminId) {
        this.updateAdminId = updateAdminId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.create_time
     *
     * @return the value of dc_admin.create_time
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.create_time
     *
     * @param createTime the value for dc_admin.create_time
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_admin.update_time
     *
     * @return the value of dc_admin.update_time
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_admin.update_time
     *
     * @param updateTime the value for dc_admin.update_time
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table dc_admin
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Admin other = (Admin) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getOperId() == null ? other.getOperId() == null : this.getOperId().equals(other.getOperId()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
                && (this.getLoginName() == null ? other.getLoginName() == null
                : this.getLoginName().equals(other.getLoginName()))
                && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
                && (this.getPassword() == null ? other.getPassword() == null
                : this.getPassword().equals(other.getPassword()))
                && (this.getPasswordSign() == null ? other.getPasswordSign() == null
                : this.getPasswordSign().equals(other.getPasswordSign()))
                && (this.getOperateSign() == null ? other.getOperateSign() == null
                : this.getOperateSign().equals(other.getOperateSign()))
                && (this.getIsLock() == null ? other.getIsLock() == null : this.getIsLock().equals(other.getIsLock()))
                && (this.getLockTime() == null ? other.getLockTime() == null
                : this.getLockTime().equals(other.getLockTime()))
                && (this.getLoginCount() == null ? other.getLoginCount() == null
                : this.getLoginCount().equals(other.getLoginCount()))
                && (this.getLastLoginTime() == null ? other.getLastLoginTime() == null
                : this.getLastLoginTime().equals(other.getLastLoginTime()))
                && (this.getLastLoginIp() == null ? other.getLastLoginIp() == null
                : this.getLastLoginIp().equals(other.getLastLoginIp()))
                && (this.getLastLogoutTime() == null ? other.getLastLogoutTime() == null
                : this.getLastLogoutTime().equals(other.getLastLogoutTime()))
                && (this.getTelephone() == null ? other.getTelephone() == null
                : this.getTelephone().equals(other.getTelephone()))
                && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
                && (this.getLevel() == null ? other.getLevel() == null : this.getLevel().equals(other.getLevel()))
                && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
                && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
                && (this.getCreateAdminId() == null ? other.getCreateAdminId() == null
                : this.getCreateAdminId().equals(other.getCreateAdminId()))
                && (this.getUpdateAdminId() == null ? other.getUpdateAdminId() == null
                : this.getUpdateAdminId().equals(other.getUpdateAdminId()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null
                : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null
                : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table dc_admin
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOperId() == null) ? 0 : getOperId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getLoginName() == null) ? 0 : getLoginName().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getPasswordSign() == null) ? 0 : getPasswordSign().hashCode());
        result = prime * result + ((getOperateSign() == null) ? 0 : getOperateSign().hashCode());
        result = prime * result + ((getIsLock() == null) ? 0 : getIsLock().hashCode());
        result = prime * result + ((getLockTime() == null) ? 0 : getLockTime().hashCode());
        result = prime * result + ((getLoginCount() == null) ? 0 : getLoginCount().hashCode());
        result = prime * result + ((getLastLoginTime() == null) ? 0 : getLastLoginTime().hashCode());
        result = prime * result + ((getLastLoginIp() == null) ? 0 : getLastLoginIp().hashCode());
        result = prime * result + ((getLastLogoutTime() == null) ? 0 : getLastLogoutTime().hashCode());
        result = prime * result + ((getTelephone() == null) ? 0 : getTelephone().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getLevel() == null) ? 0 : getLevel().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateAdminId() == null) ? 0 : getCreateAdminId().hashCode());
        result = prime * result + ((getUpdateAdminId() == null) ? 0 : getUpdateAdminId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table dc_admin
     *
     * @mbggenerated Mon Aug 06 14:50:58 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", operId=").append(operId);
        sb.append(", name=").append(name);
        sb.append(", loginName=").append(loginName);
        sb.append(", email=").append(email);
        sb.append(", password=").append(password);
        sb.append(", passwordSign=").append(passwordSign);
        sb.append(", operateSign=").append(operateSign);
        sb.append(", isLock=").append(isLock);
        sb.append(", lockTime=").append(lockTime);
        sb.append(", loginCount=").append(loginCount);
        sb.append(", lastLoginTime=").append(lastLoginTime);
        sb.append(", lastLoginIp=").append(lastLoginIp);
        sb.append(", lastLogoutTime=").append(lastLogoutTime);
        sb.append(", telephone=").append(telephone);
        sb.append(", phone=").append(phone);
        sb.append(", level=").append(level);
        sb.append(", roleId=").append(roleId);
        sb.append(", status=").append(status);
        sb.append(", createAdminId=").append(createAdminId);
        sb.append(", updateAdminId=").append(updateAdminId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    public String getStrCreateTime() {
        return DateUtil.timeToString(this.createTime, DateUtil.FORMAT_2);
    }

    public String getStrUpdateTime() {
        return DateUtil.timeToString(this.updateTime, DateUtil.FORMAT_2);
    }

    public String getStrLastLoginTime() {
        return DateUtil.timeToString(this.createTime, DateUtil.FORMAT_2);
    }

    public String getStrLastLogoutTime() {
        return DateUtil.timeToString(this.updateTime, DateUtil.FORMAT_2);
    }

    public Integer getPartnerId() {
        return partnerId;
    }

    public void setPartnerId(Integer partnerId) {
        this.partnerId = partnerId;
    }
}