/**************************************************************************
 * Copyright©2004-2016 浙江盘石信息技术股份有限公司
 * All rights reserved.
 *
 * 项目名称：互金网络平台
 * 版权说明：本软件属浙江盘石信息技术股份有限公司所有，在未获浙江盘石信息技术股份有限公司正式授权情况下，
 *          任何企业和个人，不能获取、阅读、安装、传播本软件涉及的任何受知识产权保护的内容。   
 ***************************************************************************/
package com.gndc.common.model;

import java.util.Date;
import java.util.List;

public class Right {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_right.id
     *
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_right.right_status
     *
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    private Byte rightStatus;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_right.right_name
     *
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    private String rightName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_right.right_url
     *
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    private String rightUrl;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_right.supper_id
     *
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    private Integer supperId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_right.right_type
     *
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    private Byte rightType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_right.right_order
     *
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    private Integer rightOrder;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_right.right_pic
     *
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    private String rightPic;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_right.unique_sign
     *
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    private String uniqueSign;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_right.right_level
     *
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    private Byte rightLevel;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_right.create_time
     *
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column dc_right.update_time
     *
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    private Date updateTime;

    /**
     * 下级菜单集合
     */
    private List<Right> children;

    /**
     * @return children
     */
    public List<Right> getChildren() {
        return children;
    }

    /**
     * @param children 要设置的 children
     */
    public void setChildren(List<Right> children) {
        this.children = children;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_right.id
     *
     * @return the value of dc_right.id
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_right.id
     *
     * @param id the value for dc_right.id
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_right.right_status
     *
     * @return the value of dc_right.right_status
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public Byte getRightStatus() {
        return rightStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_right.right_status
     *
     * @param rightStatus the value for dc_right.right_status
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public void setRightStatus(Byte rightStatus) {
        this.rightStatus = rightStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_right.right_name
     *
     * @return the value of dc_right.right_name
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public String getRightName() {
        return rightName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_right.right_name
     *
     * @param rightName the value for dc_right.right_name
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public void setRightName(String rightName) {
        this.rightName = rightName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_right.right_url
     *
     * @return the value of dc_right.right_url
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public String getRightUrl() {
        return rightUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_right.right_url
     *
     * @param rightUrl the value for dc_right.right_url
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public void setRightUrl(String rightUrl) {
        this.rightUrl = rightUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_right.supper_id
     *
     * @return the value of dc_right.supper_id
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public Integer getSupperId() {
        return supperId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_right.supper_id
     *
     * @param supperId the value for dc_right.supper_id
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public void setSupperId(Integer supperId) {
        this.supperId = supperId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_right.right_type
     *
     * @return the value of dc_right.right_type
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public Byte getRightType() {
        return rightType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_right.right_type
     *
     * @param rightType the value for dc_right.right_type
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public void setRightType(Byte rightType) {
        this.rightType = rightType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_right.right_order
     *
     * @return the value of dc_right.right_order
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public Integer getRightOrder() {
        return rightOrder;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_right.right_order
     *
     * @param rightOrder the value for dc_right.right_order
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public void setRightOrder(Integer rightOrder) {
        this.rightOrder = rightOrder;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_right.right_pic
     *
     * @return the value of dc_right.right_pic
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public String getRightPic() {
        return rightPic;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_right.right_pic
     *
     * @param rightPic the value for dc_right.right_pic
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public void setRightPic(String rightPic) {
        this.rightPic = rightPic;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_right.unique_sign
     *
     * @return the value of dc_right.unique_sign
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public String getUniqueSign() {
        return uniqueSign;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_right.unique_sign
     *
     * @param uniqueSign the value for dc_right.unique_sign
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public void setUniqueSign(String uniqueSign) {
        this.uniqueSign = uniqueSign;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_right.right_level
     *
     * @return the value of dc_right.right_level
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public Byte getRightLevel() {
        return rightLevel;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_right.right_level
     *
     * @param rightLevel the value for dc_right.right_level
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public void setRightLevel(Byte rightLevel) {
        this.rightLevel = rightLevel;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_right.create_time
     *
     * @return the value of dc_right.create_time
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_right.create_time
     *
     * @param createTime the value for dc_right.create_time
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column dc_right.update_time
     *
     * @return the value of dc_right.update_time
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column dc_right.update_time
     *
     * @param updateTime the value for dc_right.update_time
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table dc_right
     *
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Right other = (Right) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getRightStatus() == null ? other.getRightStatus() == null
                : this.getRightStatus().equals(other.getRightStatus()))
                && (this.getRightName() == null ? other.getRightName() == null
                : this.getRightName().equals(other.getRightName()))
                && (this.getRightUrl() == null ? other.getRightUrl() == null
                : this.getRightUrl().equals(other.getRightUrl()))
                && (this.getSupperId() == null ? other.getSupperId() == null
                : this.getSupperId().equals(other.getSupperId()))
                && (this.getRightType() == null ? other.getRightType() == null
                : this.getRightType().equals(other.getRightType()))
                && (this.getRightOrder() == null ? other.getRightOrder() == null
                : this.getRightOrder().equals(other.getRightOrder()))
                && (this.getRightPic() == null ? other.getRightPic() == null
                : this.getRightPic().equals(other.getRightPic()))
                && (this.getUniqueSign() == null ? other.getUniqueSign() == null
                : this.getUniqueSign().equals(other.getUniqueSign()))
                && (this.getRightLevel() == null ? other.getRightLevel() == null
                : this.getRightLevel().equals(other.getRightLevel()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null
                : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null
                : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table dc_right
     *
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRightStatus() == null) ? 0 : getRightStatus().hashCode());
        result = prime * result + ((getRightName() == null) ? 0 : getRightName().hashCode());
        result = prime * result + ((getRightUrl() == null) ? 0 : getRightUrl().hashCode());
        result = prime * result + ((getSupperId() == null) ? 0 : getSupperId().hashCode());
        result = prime * result + ((getRightType() == null) ? 0 : getRightType().hashCode());
        result = prime * result + ((getRightOrder() == null) ? 0 : getRightOrder().hashCode());
        result = prime * result + ((getRightPic() == null) ? 0 : getRightPic().hashCode());
        result = prime * result + ((getUniqueSign() == null) ? 0 : getUniqueSign().hashCode());
        result = prime * result + ((getRightLevel() == null) ? 0 : getRightLevel().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table dc_right
     *
     * @mbggenerated Mon Aug 06 15:44:08 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", rightStatus=").append(rightStatus);
        sb.append(", rightName=").append(rightName);
        sb.append(", rightUrl=").append(rightUrl);
        sb.append(", supperId=").append(supperId);
        sb.append(", rightType=").append(rightType);
        sb.append(", rightOrder=").append(rightOrder);
        sb.append(", rightPic=").append(rightPic);
        sb.append(", uniqueSign=").append(uniqueSign);
        sb.append(", rightLevel=").append(rightLevel);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}