package com.gndc.common.model;

import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.Date;

@Getter
@Setter
public class User extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.id
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.phone
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.uid
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.facebook_acc
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String facebookAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.fb_user_name
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String fbUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.fb_accountkit_id
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String fbAccountkitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.whatsapp_acc
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String whatsappAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.name
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.password
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.password_sign
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String passwordSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.area_id
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.head_photo
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String headPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.sex
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.birthday
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.province_id
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.city_id
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.education
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.job
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.income
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private BigDecimal income;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.collection_quantity
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Short collectionQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.reg_channel
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String regChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.reg_device
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Byte regDevice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.reg_time
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Date regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.reg_devicetoken
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String regDevicetoken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.reg_term_type
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String regTermType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.imei
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String imei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.last_login_time
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.last_login_ip
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String lastLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.last_login_device
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Byte lastLoginDevice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.last_login_devicetoken
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String lastLoginDevicetoken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.last_logout_time
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Date lastLogoutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.status
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.remark
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.app_name
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_user.app_package
     *
     * @mbggenerated Fri Aug 31 11:01:23 CST 2018
     */
    private String appPackage;

}