spring:
  cloud:
    inetutils:
      ignored-interfaces: #忽略docker0网卡以及 veth开头的网卡
        - docker0
        - veth.*
    consul:
      host: dev.gndc.consul.com
      port: 8500
      enabled: true
      discovery:
        enabled: true
        prefer-ip-address: true
        service-name: gndc-gateway
        instance-id: ${spring.application.name}-${random.uuid}
        hostname: dev.gndc.gateway.com
        tags:
          - java
          - gateway