spring:
  cloud:
    consul:
      host: gndc.consul.com
      port: 8500
      enabled: true
      discovery:
        enabled: true
        prefer-ip-address: true
        service-name: gndc-gateway
        instance-id: gndc-gateway
        hostname: gndc.gateway.com
